package com.local.polarh10monitor;

import android.Manifest;
import android.animation.ObjectAnimator;
import android.animation.PropertyValuesHolder;
import android.animation.ValueAnimator;
import android.app.Activity;
import android.app.AlertDialog;
import android.app.Dialog;
import android.annotation.SuppressLint;
import android.content.BroadcastReceiver;
import android.content.Context;
import android.content.Intent;
import android.content.IntentFilter;
import android.content.SharedPreferences;
import android.content.pm.PackageManager;
import android.content.res.ColorStateList;
import android.graphics.Typeface;
import android.graphics.drawable.ColorDrawable;
import android.graphics.drawable.GradientDrawable;
import android.graphics.drawable.RippleDrawable;
import android.net.Uri;
import android.os.Build;
import android.os.Bundle;
import android.provider.Settings;
import android.text.InputType;
import android.view.Gravity;
import android.view.View;
import android.view.ViewGroup;
import android.view.Window;
import android.widget.Button;
import android.widget.CheckBox;
import android.widget.EditText;
import android.widget.HorizontalScrollView;
import android.widget.LinearLayout;
import android.widget.ProgressBar;
import android.widget.ScrollView;
import android.widget.TextView;
import android.widget.Toast;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Locale;

@SuppressLint("SetTextI18n")
public final class MainActivity extends Activity {
    private static final int PERMISSIONS=42;
    private static final int BG=0xff071018,CARD=0xff101c28,CARD_ALT=0xff142331,LINE=0xff223548,
            TEXT=0xfff4f7fa,MUTED=0xff8fa1b3,TEAL=0xff35d4b5,BLUE=0xff65a9ff,AMBER=0xffffbd66,RED=0xffff667d;

    private TimelineView timeline;private LinearLayout ecgPage,sportsPanel;private Button ecgAction;private final java.util.concurrent.ExecutorService insightsWorker=java.util.concurrent.Executors.newSingleThreadExecutor();private int fitnessRevision;
    private LinearLayout pageHost,homePage,fitnessPage,historyPage,settingsPage,historyList,historyStats,nav,fitnessWhy,fitnessAdvice,twinDrivers;
    private TextView liveBadge,status,statusDot,device,bpm,battery,signal,today,modelState,sessionSummary,homeTab,fitnessTab,historyTab,settingsTab;
    private TextView homeBeats,homeRmssd,homeSdnn,homeSignalQuality,homeEctopy,homePauses;
    private TextView homeFitnessState,homeFitnessDetail,fitnessState,fitnessStateDetail,fitnessScore,fitnessConfidence,fitnessProfileLabel,fitnessProfileDetail,fitnessRestingHr,fitnessRmssd,fitnessTrend,fitnessMorningStatus,fitnessModerate,fitnessVigorous,fitnessStrength;
    private TextView twinDose,twinDoseDetail,twinForecast,twinInterval,twinModelStage,twinModelMetrics,twinExperiment,twinTrainingStatus;
    private ProgressBar modelProgress,fitnessMorningProgress,fitnessAdaptationProgress,fitnessActivityProgress,twinLearningProgress;
    private Button mainAction,fitnessMorningAction,twinTrainingAction,twinExperimentAction;
    private FitnessTrendView fitnessTrendView;
    private EditText historySearch;
    private EcgCanvasView ecg;
    private ObjectAnimator heartPulse;
    private boolean pendingStart,running,streaming,morningActive,initialized;
    private int morningProgress;private String morningMessage="";
    private long lastReportReadyAt;private int lastSignalEpoch;
    private int currentPage,lastEventCount=-1,lastDisplayedHeartRate=-1;
    private int historyDays=30;private String historyFilter="ALL";
    private final ArrayList<Button> periodControls=new ArrayList<>(),filterControls=new ArrayList<>();
    private final BroadcastReceiver receiver=new BroadcastReceiver(){@Override public void onReceive(Context c,Intent i){update(i);}};

    @Override protected void onCreate(Bundle state){super.onCreate(state);try{LocalRepository.get(this);buildUi();initialized=true;showPage(0);pageHost.post(()->showWelcome(false));}catch(RuntimeException error){TextView message=text("Impossible d’ouvrir les données locales. Les fichiers d’origine sont conservés. Ne désinstalle pas l’application ; conserve tes exports et contacte le développeur.",18,TEXT,false);message.setPadding(dp(24),dp(60),dp(24),dp(24));message.setBackgroundColor(BG);setContentView(message);}}

    @SuppressLint("UnspecifiedRegisterReceiverFlag")
    @Override protected void onStart(){super.onStart();if(!initialized)return;IntentFilter filter=new IntentFilter(MonitorService.ACTION_UPDATE);if(Build.VERSION.SDK_INT>=33)registerReceiver(receiver,filter,Context.RECEIVER_NOT_EXPORTED);else registerReceiver(receiver,filter);refreshHistory();refreshFitness();startHeartPulse();startService(new Intent(this,MonitorService.class).setAction(MonitorService.ACTION_STATUS));}
    @Override protected void onStop(){try{unregisterReceiver(receiver);}catch(Exception ignored){}if(heartPulse!=null)heartPulse.cancel();super.onStop();}

    @Override protected void onDestroy(){insightsWorker.shutdown();if(timeline!=null)timeline.close();super.onDestroy();}
    private void buildUi(){
        getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(BG);
        LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);root.setFitsSystemWindows(false);root.setOnApplyWindowInsetsListener((view,insets)->{view.setPadding(0,insets.getSystemWindowInsetTop(),0,insets.getSystemWindowInsetBottom());return insets;});
        pageHost=new LinearLayout(this);pageHost.setOrientation(LinearLayout.VERTICAL);
        buildPages();buildNavigation();
        LinearLayout header=row();header.setPadding(dp(20),dp(8),dp(16),dp(8));TextView brand=text("♥  H10 Rhythm Lab",21,TEXT,true);header.addView(brand,new LinearLayout.LayoutParams(0,-2,1));Button settings=outlineButton("Réglages");settings.setContentDescription("Ouvrir les réglages et ton profil");settings.setOnClickListener(v->showPage(4));header.addView(settings,lp(dp(100),dp(44),0,0,0,0));root.addView(header);
        if(getResources().getConfiguration().screenWidthDp>=600){LinearLayout content=row();nav.setOrientation(LinearLayout.VERTICAL);for(int i=0;i<nav.getChildCount();i++)nav.getChildAt(i).setLayoutParams(new LinearLayout.LayoutParams(-1,dp(64)));content.addView(nav,new LinearLayout.LayoutParams(dp(130),-1));content.addView(pageHost,new LinearLayout.LayoutParams(0,-1,1));root.addView(content,new LinearLayout.LayoutParams(-1,0,1));}
        else{root.addView(pageHost,new LinearLayout.LayoutParams(-1,0,1));root.addView(nav,new LinearLayout.LayoutParams(-1,dp(68)));}
        setContentView(root);root.requestApplyInsets();
    }

    private void buildPages(){homePage=buildHome();fitnessPage=buildFitness();historyPage=buildHistory();settingsPage=buildSettings();}

    private LinearLayout buildHome(){
        LinearLayout body=page("AUJOURD’HUI","Ton rythme. Tes repères.");ecgPage=page("ECG","Ton rythme, en direct.");ecgAction=button("Démarrer l’enregistrement",TEAL,0xff06251f);ecgAction.setOnClickListener(v->{if(running)stopMonitor();else requestAndStart();});ecgPage.addView(ecgAction,lp(-1,dp(54),0,18,0,12));Button mark=outlineButton("Marquer un ressenti");mark.setOnClickListener(v->{if(!streaming){Toast.makeText(this,"Connecte la ceinture pour enregistrer un passage.",Toast.LENGTH_LONG).show();return;}startService(new Intent(this,MonitorService.class).setAction(MonitorService.ACTION_MARK));Toast.makeText(this,"Passage marqué. Le contexte est conservé.",Toast.LENGTH_SHORT).show();});ecgPage.addView(mark,lp(-1,dp(50),0,0,0,14));
        LinearLayout hero=card();hero.setBackground(gradient(0xff15283a,CARD,0xff315269,22));LinearLayout statusRow=row();status=text("Enregistrement arrêté",14,TEXT,true);device=text("Aucune ceinture connectée",12,MUTED,false);
        LinearLayout statusTexts=new LinearLayout(this);statusTexts.setOrientation(LinearLayout.VERTICAL);statusTexts.addView(status);statusTexts.addView(device,lp(-1,-2,0,3,0,0));
        statusDot=text("♥",22,MUTED,true);statusDot.setGravity(Gravity.CENTER);statusDot.setBackground(gradient(0xff3b1722,0xff1e202b,0xff6b2c40,16));statusDot.setContentDescription("Cœur et état de l’enregistrement");statusRow.addView(statusDot,lp(dp(38),dp(38),0,0,10,0));statusRow.addView(statusTexts,new LinearLayout.LayoutParams(0,-2,1));hero.addView(statusRow);
        bpm=text("--",58,TEXT,true);bpm.setGravity(Gravity.CENTER_HORIZONTAL);hero.addView(bpm,lp(-1,-2,0,18,0,0));TextView bpmLabel=text("battements par minute",13,MUTED,false);bpmLabel.setGravity(Gravity.CENTER_HORIZONTAL);hero.addView(bpmLabel);
        mainAction=button("Démarrer l’enregistrement",TEAL,0xff06251f);hero.addView(mainAction,lp(-1,dp(54),0,20,0,0));hero.addView(text("MODE LABORATOIRE : aucune alerte cardiaque sonore ou vibrante. Enregistrement et hypothèses à relire uniquement. Ne remplace pas un dispositif médical.",12,AMBER,false),lp(-1,-2,0,12,0,0));mainAction.setOnClickListener(v->{if(running)stopMonitor();else requestAndStart();});body.addView(hero,lp(-1,-2,0,16,0,12));

        LinearLayout quick=row();battery=miniCard(quick,"Ceinture","-- %",BLUE);signal=miniCard(quick,"Signal","En attente",TEAL);today=miniCard(quick,"Aujourd’hui",EventHistory.countToday(this)+" passage(s)",AMBER);body.addView(quick,lp(-1,-2,0,0,0,14));
        LinearLayout formPreview=card();LinearLayout formHead=row();LinearLayout formWords=new LinearLayout(this);formWords.setOrientation(LinearLayout.VERTICAL);homeFitnessState=text("Ton suivi de forme",17,TEXT,true);homeFitnessDetail=text("Un bilan au calme, tes séances et tes tendances.",12,MUTED,false);formWords.addView(homeFitnessState);formWords.addView(homeFitnessDetail,lp(-1,-2,0,5,0,0));TextView formIcon=text("♥",27,TEAL,true);formIcon.setGravity(Gravity.CENTER);formIcon.setBackground(round(0xff123a34,0xff246a5e,16));formHead.addView(formWords,new LinearLayout.LayoutParams(0,-2,1));formHead.addView(formIcon,lp(dp(48),dp(48),0,0,0,0));formPreview.addView(formHead);Button openForm=outlineButton("Ouvrir le suivi de forme");openForm.setOnClickListener(v->showPage(2));formPreview.addView(openForm,lp(-1,dp(46),0,13,0,0));body.addView(formPreview,lp(-1,-2,0,0,0,14));
        LinearLayout liveStats=card();liveStats.addView(text("Indicateurs de la session",18,TEXT,true));LinearLayout statsA=row();homeBeats=sessionMetric(statsA,"Battements","--",TEXT);homeRmssd=sessionMetric(statsA,"RMSSD · rapide","--",BLUE);homeSdnn=sessionMetric(statsA,"SDNN · globale","--",BLUE);liveStats.addView(statsA,lp(-1,-2,0,12,0,0));LinearLayout statsB=row();homeSignalQuality=sessionMetric(statsB,"Signal propre","--",TEAL);homeEctopy=sessionMetric(statsB,"En avance","0",AMBER);homePauses=sessionMetric(statsB,"Pauses","0",RED);liveStats.addView(statsB,lp(-1,-2,0,7,0,0));liveStats.addView(text("RMSSD suit surtout les variations d’un battement au suivant. SDNN résume la dispersion globale des intervalles sur la période analysée.",11,MUTED,false),lp(-1,-2,0,10,0,0));body.addView(liveStats,lp(-1,-2,0,0,0,14));
        LinearLayout chart=card();LinearLayout chartHead=row();TextView chartTitle=text("Tracé ECG",18,TEXT,true);TextView live=text("EN ATTENTE",10,TEAL,true);liveBadge=live;live.setGravity(Gravity.CENTER);live.setPadding(dp(10),dp(5),dp(10),dp(5));live.setBackground(round(0xff102e2c,0xff246a5e,30));chartHead.addView(chartTitle,new LinearLayout.LayoutParams(0,-2,1));chartHead.addView(live);chart.addView(chartHead);ecg=new EcgCanvasView(this);chart.addView(ecg,lp(-1,dp(260),0,14,0,0));ecgPage.addView(chart,lp(-1,-2,0,0,0,14));

        LinearLayout personal=card();personal.addView(text("Analyse personnalisée",18,TEXT,true));MorphologyModel savedModel=MorphologyModel.deserialize(getSharedPreferences("monitor",MODE_PRIVATE).getString("morphology_state_v1",""));modelState=text(savedModel.isReady()?"Modèle prêt • "+savedModel.normalCount()+" battements de référence":"Apprentissage • "+savedModel.normalCount()+" / "+MorphologyModel.BASELINE_TARGET+" battements propres",13,MUTED,false);personal.addView(modelState,lp(-1,-2,0,8,0,10));modelProgress=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);modelProgress.setMax(MorphologyModel.BASELINE_TARGET);modelProgress.setProgress(savedModel.normalCount());modelProgress.setProgressTintList(ColorStateList.valueOf(TEAL));modelProgress.setProgressBackgroundTintList(ColorStateList.valueOf(LINE));personal.addView(modelProgress,lp(-1,dp(7),0,0,0,10));personal.addView(text("Deux analyses locales : un modèle expérimental entraîné sur des ECG publics et ta référence personnelle. La classe ESA est désactivée : ses essais sont insuffisants. Un battement indéterminé n’est pas déclaré normal.",12,MUTED,false));personal.addView(text(getString(R.string.model_attribution),11,MUTED,false),lp(-1,-2,0,10,0,0));ecgPage.addView(personal,lp(-1,-2,0,0,0,14));

        LinearLayout watched=card();watched.addView(text("Ce que l’application surveille",18,TEXT,true));watched.addView(feature("Battements en avance","Recherche une rupture nette par rapport à ton rythme habituel."));watched.addView(feature("Pauses inhabituelles","Signale une absence prolongée de battement sur un signal propre."));watched.addView(feature("Rythme anormalement rapide, lent ou irrégulier","Conserve le passage complet pour pouvoir le vérifier ensuite."));ecgPage.addView(watched,lp(-1,-2,0,0,0,14));
        sessionSummary=text("Aucun passage détecté pendant cette session.",12,MUTED,false);body.addView(sessionSummary,lp(-1,-2,4,0,4,12));return body;
    }

    private LinearLayout buildFitness(){
        LinearLayout body=page("FORME","Comprends tes habitudes.");sportsPanel=card();

        LinearLayout hero=card();hero.setBackground(gradient(0xff173a42,0xff111c28,0xff387769,23));
        LinearLayout top=row();LinearLayout words=new LinearLayout(this);words.setOrientation(LinearLayout.VERTICAL);
        fitnessState=text("Bilan du jour à réaliser",23,TEXT,true);fitnessStateDetail=text("Le modèle compare ta réponse à ton propre fonctionnement.",13,MUTED,false);
        words.addView(fitnessState);words.addView(fitnessStateDetail,lp(-1,-2,0,6,0,0));fitnessScore=text("Repères",12,TEAL,true);fitnessScore.setGravity(Gravity.CENTER);fitnessScore.setBackground(round(0xff123a34,0xff246a5e,30));
        top.addView(words,new LinearLayout.LayoutParams(0,-2,1));top.addView(fitnessScore,lp(dp(72),dp(38),0,0,0,0));hero.addView(top);
        fitnessConfidence=text("Référence en construction",11,BLUE,true);hero.addView(fitnessConfidence,lp(-1,-2,0,14,0,0));body.addView(hero,lp(-1,-2,0,16,0,14));

        LinearLayout decision=card();decision.addView(text("Préparer ta prochaine séance",19,TEXT,true));twinDose=text("Mesure nécessaire",24,TEAL,true);decision.addView(twinDose,lp(-1,-2,0,10,0,3));twinDoseDetail=text("Compare uniquement des séances déjà représentées dans ton historique.",13,TEXT,false);decision.addView(twinDoseDetail);View divider=new View(this);divider.setBackgroundColor(LINE);decision.addView(divider,lp(-1,dp(1),0,14,0,12));twinForecast=text("Aucune prévision aujourd’hui.",13,BLUE,true);decision.addView(twinForecast);twinInterval=text("Le suivi s’enrichit avec tes bilans.",11,MUTED,false);decision.addView(twinInterval,lp(-1,-2,0,5,0,0));body.addView(decision,lp(-1,-2,0,0,0,14));

        LinearLayout metrics=row();fitnessRestingHr=miniCard(metrics,"FC repos","--",RED);fitnessRmssd=miniCard(metrics,"VFC RMSSD","--",BLUE);fitnessTrend=miniCard(metrics,"Tendance 7 j","--",TEAL);body.addView(metrics,lp(-1,-2,0,0,0,14));

        LinearLayout check=card();check.addView(text("Point de mesure",19,TEXT,true));check.addView(text("3 minutes au calme, idéalement au réveil. Les battements anormaux, mouvements et zones bruitées sont exclus avant l’apprentissage.",12,MUTED,false),lp(-1,-2,0,7,0,10));fitnessMorningStatus=text("Aucun bilan enregistré aujourd’hui.",12,AMBER,false);check.addView(fitnessMorningStatus);fitnessMorningProgress=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);fitnessMorningProgress.setMax(100);fitnessMorningProgress.setProgressTintList(ColorStateList.valueOf(TEAL));fitnessMorningProgress.setProgressBackgroundTintList(ColorStateList.valueOf(LINE));check.addView(fitnessMorningProgress,lp(-1,dp(7),0,10,0,10));fitnessMorningAction=button("Lancer le bilan de 3 minutes",TEAL,0xff06251f);fitnessMorningAction.setOnClickListener(v->{if(morningActive)startService(new Intent(this,MonitorService.class).setAction(MonitorService.ACTION_CANCEL_MORNING));else showMorningDialog();});check.addView(fitnessMorningAction,lp(-1,dp(52),0,0,0,0));body.addView(check,lp(-1,-2,0,0,0,14));

        body.addView(sportsPanel,lp(-1,-2,0,0,0,14));
        LinearLayout explain=card();explain.addView(text("Ce qui pèse dans la décision",19,TEXT,true));explain.addView(text("Retrouve les mesures et le contexte de ce bilan.",11,MUTED,false),lp(-1,-2,0,5,0,0));fitnessWhy=new LinearLayout(this);fitnessWhy.setOrientation(LinearLayout.VERTICAL);explain.addView(fitnessWhy);body.addView(explain,lp(-1,-2,0,0,0,14));

        LinearLayout learned=card();learned.addView(text("Ce que le modèle apprend sur toi",19,TEXT,true));learned.addView(text("Associations personnelles calculées uniquement quand il existe assez de journées avec et sans le facteur.",11,MUTED,false),lp(-1,-2,0,5,0,2));twinDrivers=new LinearLayout(this);twinDrivers.setOrientation(LinearLayout.VERTICAL);learned.addView(twinDrivers);body.addView(fold("Associations observées",learned),lp(-1,-2,0,0,0,14));

        LinearLayout experiment=card();experiment.addView(text("Expérience personnelle",19,TEXT,true));twinExperiment=text("Le modèle prépare une hypothèse à partir de tes journées comparables.",13,TEXT,false);experiment.addView(twinExperiment,lp(-1,-2,0,8,0,0));experiment.addView(text("Une association n’est jamais présentée comme une cause. L’application indique toujours le nombre d’observations.",10,MUTED,false),lp(-1,-2,0,8,0,8));twinExperimentAction=outlineButton("Tester un coucher 30 min plus tôt");twinExperimentAction.setOnClickListener(v->toggleTwinExperiment());experiment.addView(twinExperimentAction,lp(-1,dp(48),0,3,0,0));body.addView(fold("Expérience de sommeil",experiment),lp(-1,-2,0,0,0,14));

        LinearLayout trends=card();trends.addView(text("Réponse personnelle",19,TEXT,true));trends.addView(text("Deux graphiques, avec leurs unités et leurs dates. Les jours sans bilan restent absents.",11,MUTED,false),lp(-1,-2,0,5,0,4));fitnessTrendView=new FitnessTrendView(this);trends.addView(fitnessTrendView,lp(-1,dp(270),0,4,0,0));LinearLayout ranges=row();for(int range:new int[]{7,30,90}){Button choice=smallButton(range+" jours");ranges.addView(choice,new LinearLayout.LayoutParams(0,dp(48),1));choice.setOnClickListener(v->fitnessTrendView.setDays(range));}trends.addView(ranges);body.addView(trends,lp(-1,-2,0,0,0,14));

        LinearLayout passport=card();passport.addView(text("Ce que l’application a appris",19,TEXT,true));twinModelStage=text("Collecte initiale",18,BLUE,true);passport.addView(twinModelStage,lp(-1,-2,0,8,0,3));twinModelMetrics=text("0 transition évaluée",12,MUTED,false);passport.addView(twinModelMetrics);twinLearningProgress=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);twinLearningProgress.setMax(30);twinLearningProgress.setProgressTintList(ColorStateList.valueOf(BLUE));twinLearningProgress.setProgressBackgroundTintList(ColorStateList.valueOf(LINE));passport.addView(twinLearningProgress,lp(-1,dp(7),0,12,0,9));fitnessAdvice=new LinearLayout(this);fitnessAdvice.setOrientation(LinearLayout.VERTICAL);passport.addView(fitnessAdvice);body.addView(fold("Apprentissage et conseils",passport),lp(-1,-2,0,0,0,14));

        LinearLayout activity=card();activity.addView(text("Charge observée sur 7 jours",19,TEXT,true));LinearLayout activityValues=row();fitnessModerate=sessionMetric(activityValues,"Modérée","0 min",TEAL);fitnessVigorous=sessionMetric(activityValues,"Soutenue","0 min",AMBER);fitnessStrength=sessionMetric(activityValues,"Renforcement","À renseigner",BLUE);activity.addView(activityValues,lp(-1,-2,0,12,0,8));fitnessActivityProgress=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);fitnessActivityProgress.setMax(150);fitnessActivityProgress.setProgressTintList(ColorStateList.valueOf(TEAL));fitnessActivityProgress.setProgressBackgroundTintList(ColorStateList.valueOf(LINE));activity.addView(fitnessActivityProgress,lp(-1,dp(7),0,5,0,8));activity.addView(text("Une minute soutenue compte comme deux minutes équivalentes modérées. Seul le temps porté avec la H10 est observé.",11,MUTED,false));body.addView(fold("Activité mesurée",activity),lp(-1,-2,0,0,0,14));

        LinearLayout feedback=card();feedback.addView(text("Apprendre de la dernière séance",19,TEXT,true));feedback.addView(text("La fréquence cardiaque mesure la charge interne ; ton ressenti complète ce que le capteur ne peut pas savoir.",11,MUTED,false),lp(-1,-2,0,5,0,8));twinTrainingStatus=text("Aucune séance récente à noter.",12,MUTED,false);feedback.addView(twinTrainingStatus);twinTrainingAction=outlineButton("Noter l’effort perçu");twinTrainingAction.setOnClickListener(v->showSessionRatingDialog());feedback.addView(twinTrainingAction,lp(-1,dp(48),0,11,0,0));body.addView(fold("Noter une séance H10",feedback),lp(-1,-2,0,0,0,14));

        LinearLayout profileCard=card();profileCard.addView(text("Contexte du modèle",19,TEXT,true));fitnessProfileLabel=text("Profil à compléter",18,TEAL,true);fitnessProfileDetail=text("Âge, habitudes et traitements : retrouve le rôle de chaque information.",12,MUTED,false);profileCard.addView(fitnessProfileLabel,lp(-1,-2,0,9,0,4));profileCard.addView(fitnessProfileDetail);fitnessAdaptationProgress=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);fitnessAdaptationProgress.setMax(100);fitnessAdaptationProgress.setVisibility(View.GONE);fitnessAdaptationProgress.setProgressTintList(ColorStateList.valueOf(BLUE));fitnessAdaptationProgress.setProgressBackgroundTintList(ColorStateList.valueOf(LINE));profileCard.addView(fitnessAdaptationProgress,lp(-1,dp(7),0,12,0,12));Button editProfile=outlineButton("Modifier mon contexte");editProfile.setOnClickListener(v->showProfileDialog());profileCard.addView(editProfile,lp(-1,dp(48),0,0,0,0));body.addView(fold("Ton profil",profileCard),lp(-1,-2,0,0,0,14));

        LinearLayout privacy=card();privacy.addView(text("Apprentissage privé et vérifiable",18,TEXT,true));privacy.addView(text("Les coefficients, bilans et prévisions restent sur ce téléphone. Une prévision ML n’apparaît que si elle a mieux fonctionné que « demain ressemble à aujourd’hui » sur ton historique.",12,MUTED,false),lp(-1,-2,0,7,0,10));Button eraseFitness=dangerButton("Réinitialiser le suivi de forme");eraseFitness.setOnClickListener(v->confirmFitnessReset());privacy.addView(eraseFitness,lp(-1,dp(48),0,0,0,0));body.addView(fold("Données et remise à zéro",privacy),lp(-1,-2,0,0,0,18));return body;
    }

    private LinearLayout fold(String title,View content){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);Button toggle=outlineButton(title+"  +");box.addView(toggle,lp(-1,dp(56),0,0,0,0));content.setVisibility(View.GONE);box.addView(content);toggle.setOnClickListener(v->{boolean show=content.getVisibility()!=View.VISIBLE;content.setVisibility(show?View.VISIBLE:View.GONE);toggle.setText(title+(show?"  −":"  +"));});return box;}

    private void refreshFitness(){
        if(fitnessState==null||insightsWorker.isShutdown())return;int revision=++fitnessRevision;insightsWorker.execute(()->{FitnessInsights.Summary s=FitnessInsights.summarize(this);List<FitnessInsights.Morning> mornings=FitnessInsights.mornings(this);AdaptiveTwin.Report twin=AdaptiveTwin.analyze(this,s);runOnUiThread(()->{if(!isDestroyed()&&revision==fitnessRevision)applyFitness(s,mornings,twin);});});
    }
    private void applyFitness(FitnessInsights.Summary s,List<FitnessInsights.Morning> mornings,AdaptiveTwin.Report twin){
        SportsPanel.populate(this,sportsPanel,this::refreshFitness);
        fitnessState.setText(s.state);fitnessStateDetail.setText(s.hasToday?"Réponse personnelle du jour • pas un diagnostic":s.stateDetail);fitnessScore.setText(twin.reliable?"Suivi":"Repères");fitnessConfidence.setText(twin.stage+" • "+s.totalMornings+" bilan(s)");
        int stateColor=s.state.contains("inhabituel")||s.state.contains("réduite")?RED:s.state.contains("Charge")?AMBER:TEAL;fitnessState.setTextColor(stateColor);homeFitnessState.setText(s.state);homeFitnessState.setTextColor(stateColor);homeFitnessDetail.setText(s.hasToday?"Ton bilan et tes tendances sont disponibles.":"Trois minutes au calme pour préparer ton bilan.");
        twinDose.setText(twin.doseLow==0&&twin.doseHigh==0?twin.doseTitle:twin.doseLow+"–"+twin.doseHigh+" min équivalentes");twinDoseDetail.setText(twin.doseDetail);twinForecast.setText(twin.forecast);twinInterval.setText(twin.interval.isEmpty()?"Les estimations apparaissent quand les données le permettent.":twin.interval);
        FitnessInsights.Morning current=s.hasToday?s.current:null;fitnessRestingHr.setText(current!=null?String.format(Locale.FRANCE,"%.0f bpm",current.restingHr):s.baselineHr>0?String.format(Locale.FRANCE,"réf. %.0f",s.baselineHr):"--");fitnessRmssd.setText(current!=null?String.format(Locale.FRANCE,"%.0f ms",current.rmssd):s.baselineRmssd>0?String.format(Locale.FRANCE,"réf. %.0f",s.baselineRmssd):"--");fitnessTrend.setText(s.totalMornings<4?"--":String.format(Locale.FRANCE,"%+.0f %%",s.hrvTrendPercent));
        fitnessWhy.removeAllViews();for(String item:twin.factors)fitnessWhy.addView(infoLine("●",item,BLUE));
        twinDrivers.removeAllViews();for(AdaptiveTwin.Driver d:twin.drivers){String detail=d.interpretation+" • "+d.exposed+" avec / "+d.control+" sans";twinDrivers.addView(infoLine(d.usable?d.effect<-.35?"↓":d.effect>.35?"↑":"≈":"…",d.name+" — "+detail,d.usable?d.effect<-.35?RED:TEAL:MUTED));}twinExperiment.setText(twin.experiment);AdaptiveTwin.ExperimentState experiment=AdaptiveTwin.experiment(this);twinExperimentAction.setText(experiment.active?"Terminer cette expérience":"Tester un coucher 30 min plus tôt");
        twinModelStage.setText(twin.stage);twinModelStage.setTextColor(twin.reliable?TEAL:twin.samples>=21?AMBER:BLUE);twinLearningProgress.setProgress(Math.min(30,twin.samples));String performance=twin.evaluated==0?"Pas encore de journée testable":String.format(Locale.FRANCE,"Erreur ML %.2f • référence naïve %.2f • %d prévision(s) testée(s)",twin.modelMae,twin.naiveMae,twin.evaluated);twinModelMetrics.setText(twin.samples+" transition(s) apprises • "+performance);fitnessAdvice.removeAllViews();fitnessAdvice.addView(infoLine(twin.reliable?"✓":"○",twin.status,twin.reliable?TEAL:AMBER));
        fitnessProfileLabel.setText(s.profile.complete()?(s.profile.sport.isEmpty()?"Contexte enregistré":s.profile.sport)+(!s.profile.goal.isEmpty()?" • "+s.profile.goal:""):"Profil à compléter");fitnessAdaptationProgress.setProgress(s.adaptationScore);if(s.profile.complete()){String context="Âge : zones estimées"+(s.profile.hrMedication?" suspendues (traitement déclaré)":"")+" • IMC contextuel : "+String.format(Locale.FRANCE,"%.1f",s.profile.bmi())+"\nL’activité et le ressenti complètent les mesures.";if(!s.profile.sex.isEmpty())context+="\nSexe : "+s.profile.sex+" — contexte facultatif, aucun bonus ou malus quotidien";fitnessProfileDetail.setText(context);}else fitnessProfileDetail.setText("Complète les informations essentielles pour contextualiser les zones et le démarrage. Le modèle personnel prendra ensuite le relais.");
        fitnessModerate.setText(s.observedModerate+" min");fitnessVigorous.setText(s.observedVigorous+" min");fitnessStrength.setText(s.profile.complete()?s.profile.strengthDays+" j déclarés":"À renseigner");fitnessActivityProgress.setProgress(Math.min(150,s.observedModerate+2*s.observedVigorous));fitnessTrendView.setValues(mornings);SessionHistory.Record unrated=AdaptiveTwin.latestSessionToRate(this);twinTrainingStatus.setText(unrated==null?"Toutes les séances récentes sont renseignées.":"Séance du "+new SimpleDateFormat("dd/MM à HH:mm",Locale.FRANCE).format(new Date(unrated.startMs))+" • "+duration(unrated.endMs-unrated.startMs));twinTrainingAction.setEnabled(unrated!=null);twinTrainingAction.setAlpha(unrated==null?.45f:1f);
        fitnessMorningProgress.setProgress(morningActive?morningProgress:s.hasToday?100:0);fitnessMorningAction.setText(morningActive?"Annuler le bilan":s.hasToday?"Refaire le bilan du jour":"Lancer le bilan de 3 minutes");
        if(morningActive)fitnessMorningStatus.setText(morningMessage.isEmpty()?"Mesure en cours…":morningMessage);else if(!morningMessage.isEmpty())fitnessMorningStatus.setText(morningMessage);else fitnessMorningStatus.setText(s.hasToday?"Bilan d’aujourd’hui enregistré • signal "+String.format(Locale.FRANCE,"%.0f %%",s.current.quality):"Aucun bilan enregistré aujourd’hui.");
    }

    private void showSessionRatingDialog(){
        SessionHistory.Record session=AdaptiveTwin.latestSessionToRate(this);if(session==null){Toast.makeText(this,"Aucune séance récente en attente.",Toast.LENGTH_SHORT).show();return;}
        LinearLayout form=new LinearLayout(this);form.setOrientation(LinearLayout.VERTICAL);form.setPadding(dp(18),dp(8),dp(18),dp(8));form.addView(text("À quel point cette séance a-t-elle été difficile ?",13,TEXT,true));form.addView(text("1 = très facile • 10 = effort maximal. Cette note ajuste la charge que le modèle relie au bilan du lendemain.",11,MUTED,false),lp(-1,-2,0,5,0,8));EditText rpe=formInput("Effort perçu de 1 à 10",5,true);form.addView(rpe,lp(-1,dp(50),0,4,0,7));CheckBox completed=styledCheck("Séance terminée comme prévu",true);form.addView(completed);
        AlertDialog dialog=new AlertDialog.Builder(this).setTitle("Retour sur la séance").setView(form).setNegativeButton("Plus tard",null).setPositiveButton("Enregistrer",null).create();dialog.setOnShowListener(ignored->dialog.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(v->{int value=intValue(rpe);if(value<1||value>10){Toast.makeText(this,"Choisis une valeur entre 1 et 10.",Toast.LENGTH_LONG).show();return;}AdaptiveTwin.saveSessionRating(this,session.startMs,value,completed.isChecked());dialog.dismiss();refreshFitness();Toast.makeText(this,"Le modèle utilisera ce retour au prochain apprentissage.",Toast.LENGTH_SHORT).show();}));dialog.show();
    }

    private void toggleTwinExperiment(){AdaptiveTwin.ExperimentState state=AdaptiveTwin.experiment(this);if(state.active)new AlertDialog.Builder(this).setTitle("Terminer l’expérience ?").setMessage("Les observations déjà enregistrées restent dans les bilans, mais aucun nouveau matin ne sera ajouté à ce test.").setNegativeButton("Continuer",null).setPositiveButton("Terminer",(d,w)->{AdaptiveTwin.stopExperiment(this);refreshFitness();}).show();else new AlertDialog.Builder(this).setTitle("Tester un coucher plus tôt").setMessage("Pendant environ 12 nuits, essaie certains soirs de te coucher 30 minutes plus tôt. Chaque matin, indique simplement si tu as respecté l’objectif. Le résultat restera masqué tant qu’il n’existe pas assez de journées dans les deux groupes.\n\nCe test observe une association personnelle, pas une preuve médicale.").setNegativeButton("Annuler",null).setPositiveButton("Commencer",(d,w)->{AdaptiveTwin.startSleepExperiment(this);refreshFitness();Toast.makeText(this,"L’expérience commence ce soir.",Toast.LENGTH_LONG).show();}).show();}

    private void showProfileDialog(){ProfileWizard.show(this,this::refreshFitness);}

    private void showMorningDialog(){
        if(!FitnessInsights.profile(this).complete()){Toast.makeText(this,"Complète d’abord ton profil.",Toast.LENGTH_LONG).show();showProfileDialog();return;}if(!streaming){Toast.makeText(this,"Démarre l’enregistrement et attends que le signal soit indiqué comme bon.",Toast.LENGTH_LONG).show();return;}
        LinearLayout form=new LinearLayout(this);form.setOrientation(LinearLayout.VERTICAL);form.setPadding(dp(18),dp(8),dp(18),dp(8));form.addView(text("Renseigne le contexte avant de rester immobile et de respirer naturellement.",12,MUTED,false),lp(-1,-2,0,0,0,8));EditText sleep=formInput("Qualité du sommeil de 1 à 5",3,true),stress=formInput("Stress de 1 à 5",3,true),soreness=formInput("Fatigue musculaire de 1 à 5",3,true);form.addView(sleep,lp(-1,dp(50),0,5,0,5));form.addView(stress,lp(-1,dp(50),0,5,0,5));form.addView(soreness,lp(-1,dp(50),0,5,0,5));CheckBox symptoms=styledCheck("J’ai des symptômes inhabituels",false),alcohol=styledCheck("Alcool consommé récemment",false),hard=styledCheck("Séance difficile dans les dernières 24 h",false);form.addView(symptoms);form.addView(alcohol);form.addView(hard);AdaptiveTwin.ExperimentState experiment=AdaptiveTwin.experiment(this);CheckBox experimentFollowed=styledCheck("Hier : objectif « coucher 30 min plus tôt » respecté",false);if(experiment.active){form.addView(text("Expérience personnelle",12,TEAL,true),lp(-1,-2,0,10,0,0));form.addView(experimentFollowed);}
        ScrollView morningScroll=new ScrollView(this);morningScroll.addView(form);AlertDialog dialog=new AlertDialog.Builder(this).setTitle("Préparer le bilan matinal").setView(morningScroll).setNegativeButton("Annuler",null).setPositiveButton("Commencer",null).create();dialog.setOnShowListener(ignored->dialog.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(v->{int sl=intValue(sleep),st=intValue(stress),so=intValue(soreness);if(sl<1||sl>5||st<1||st>5||so<1||so>5){Toast.makeText(this,"Les trois notes doivent être comprises entre 1 et 5.",Toast.LENGTH_LONG).show();return;}Intent intent=new Intent(this,MonitorService.class).setAction(MonitorService.ACTION_START_MORNING).putExtra("sleep",sl).putExtra("stress",st).putExtra("soreness",so).putExtra("symptoms",symptoms.isChecked()).putExtra("alcohol",alcohol.isChecked()).putExtra("hardTraining",hard.isChecked()).putExtra("experimentId",experiment.active?experiment.id:"").putExtra("experimentFollowed",experiment.active&&experimentFollowed.isChecked());startService(intent);morningActive=true;morningProgress=0;morningMessage="Stabilisation de la mesure…";refreshFitness();dialog.dismiss();}));dialog.show();
    }

    private EditText formInput(String hint,int value,boolean numeric){return formInput(hint,value==0?"":String.valueOf(value),numeric);}
    private EditText formInput(String hint,String value,boolean numeric){EditText field=new EditText(this);field.setHint(hint);field.setHintTextColor(MUTED);field.setTextColor(TEXT);field.setText(value);field.setTextSize(13);field.setSingleLine(true);field.setPadding(dp(13),0,dp(13),0);field.setBackground(round(CARD_ALT,LINE,13));if(numeric)field.setInputType(InputType.TYPE_CLASS_NUMBER);return field;}
    private CheckBox styledCheck(String label,boolean checked){CheckBox box=new CheckBox(this);box.setText(label);box.setTextColor(TEXT);box.setTextSize(12);box.setChecked(checked);box.setButtonTintList(new ColorStateList(new int[][]{new int[]{android.R.attr.state_checked},new int[]{}},new int[]{TEAL,MUTED}));return box;}
    private void addProfileField(LinearLayout form,String label,String help,EditText field){form.addView(text(label,12,TEXT,true),lp(-1,-2,0,12,0,3));form.addView(text(help,10,MUTED,false));form.addView(field,lp(-1,dp(50),0,6,0,0));}
    private void styleChoices(Button[] buttons,String[] values,String selected){for(int i=0;i<buttons.length;i++){boolean active=values[i].equals(selected);buttons[i].setTextColor(active?0xff06251f:MUTED);buttons[i].setBackground(ripple(active?TEAL:CARD_ALT,active?TEAL:LINE,13));}}
    private int intValue(EditText field){try{return Integer.parseInt(field.getText().toString().trim());}catch(Exception ignored){return 0;}}
    private View infoLine(String icon,String value,int color){LinearLayout line=row();TextView mark=text(icon,13,color,true);line.addView(mark,lp(dp(22),-2,0,0,5,0));line.addView(text(value,12,MUTED,false),new LinearLayout.LayoutParams(0,-2,1));line.setPadding(0,dp(10),0,0);return line;}
    private void confirmFitnessReset(){if(running){Toast.makeText(this,"Arrête l’enregistrement avant de remettre le suivi à zéro.",Toast.LENGTH_LONG).show();return;}new AlertDialog.Builder(this).setTitle("Réinitialiser le suivi de forme ?").setMessage("Le profil, les bilans matinaux, les coefficients appris et les prévisions seront supprimés. Les ECG, rapports et événements resteront disponibles.").setNegativeButton("Annuler",null).setPositiveButton("Effacer",(dialog,which)->{insightsWorker.execute(()->{FitnessInsights.clear(this);AdaptiveTwin.clear(this);TrainingJournal.clear(this);runOnUiThread(()->{morningMessage="";refreshFitness();Toast.makeText(this,"Suivi de forme remis à zéro.",Toast.LENGTH_SHORT).show();});});}).show();}

    private LinearLayout buildHistory(){
        LinearLayout body=page("HISTORIQUE","Retrouve ce qui compte.");timeline=new TimelineView(this,record->{ScrollView content=new ScrollView(this);content.addView(historyCard(record));new AlertDialog.Builder(this).setView(content).setPositiveButton("Fermer",null).show();});body.addView(timeline,lp(-1,-2,0,16,0,12));Button erase=dangerButton("Effacer tout l’historique");erase.setOnClickListener(v->confirmDeleteReports());body.addView(erase,lp(-1,dp(52),0,8,0,0));return body;
    }

    private LinearLayout buildSettings(){
        LinearLayout body=page("RÉGLAGES","Seulement les options qui comptent.");SharedPreferences prefs=getSharedPreferences("settings",MODE_PRIVATE);
        LinearLayout alertsCard=card();alertsCard.addView(text("Alertes",18,TEXT,true));CheckBox alerts=new CheckBox(this);alerts.setText("Alertes cardiaques désactivées dans cette version laboratoire");alerts.setTextColor(TEXT);alerts.setTextSize(13);alerts.setButtonTintList(new ColorStateList(new int[][]{new int[]{android.R.attr.state_checked},new int[]{}},new int[]{TEAL,MUTED}));alerts.setChecked(false);alerts.setEnabled(false);alerts.setOnCheckedChangeListener((button,checked)->prefs.edit().putBoolean("alerts",checked).apply());alertsCard.addView(alerts,lp(-1,-2,0,8,0,5));Button notifications=outlineButton("Notifications techniques uniquement");notifications.setOnClickListener(v->openNotificationSettings());alertsCard.addView(notifications,lp(-1,dp(48),0,5,0,0));body.addView(alertsCard,lp(-1,-2,0,16,0,14));
        Button zones=outlineButton("Mes zones d’activité");zones.setOnClickListener(v->TrainingZones.show(this));body.addView(zones,lp(-1,dp(52),0,0,0,14));
        LinearLayout background=card();background.addView(text("Enregistrement écran éteint",18,TEXT,true));background.addView(text("Android doit autoriser l’application à fonctionner sans restriction pour éviter les coupures.",13,MUTED,false),lp(-1,-2,0,7,0,10));Button batterySettings=outlineButton("Autoriser le fonctionnement continu");batterySettings.setOnClickListener(v->openBatterySettings());background.addView(batterySettings,lp(-1,dp(48),0,0,0,0));body.addView(background,lp(-1,-2,0,0,0,14));
        LinearLayout model=card();model.addView(text("Modèle personnel",18,TEXT,true));model.addView(text("L’étalonnage et les exemples d’artefacts restent enregistrés uniquement sur ce téléphone. Marquer un passage comme Artefact aide à reconnaître ensuite une forme similaire.",13,MUTED,false),lp(-1,-2,0,7,0,10));Button reset=outlineButton("Recommencer l’apprentissage");reset.setTextColor(RED);reset.setOnClickListener(v->confirmModelReset());model.addView(reset,lp(-1,dp(48),0,0,0,0));body.addView(model,lp(-1,-2,0,0,0,14));
        LinearLayout retention=card();retention.addView(text("Durée de conservation du signal",18,TEXT,true));retention.addView(text("24 h ≈ 135 Mo · 72 h ≈ 405 Mo · 7 j ≈ 945 Mo. Les passages enregistrés restent conservés jusqu’à leur suppression.",12,MUTED,false));android.widget.Spinner keep=new android.widget.Spinner(this);keep.setAdapter(new android.widget.ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"24 heures","72 heures","7 jours"}));int hours=prefs.getInt("retentionHours",24);keep.setSelection(hours==168?2:hours==72?1:0);keep.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onNothingSelected(android.widget.AdapterView<?> parent){}public void onItemSelected(android.widget.AdapterView<?> parent,View view,int pos,long id){prefs.edit().putInt("retentionHours",new int[]{24,72,168}[pos]).apply();}});retention.addView(keep);body.addView(retention,lp(-1,-2,0,0,0,14));LinearLayout storage=dangerCard();storage.addView(text("Repartir avec un historique vide",18,TEXT,true));storage.addView(text("Supprime les rapports PDF, les ECG bruts, les signaux glissants et les résumés de sessions. Ton profil morphologique personnel reste conservé.",13,MUTED,false),lp(-1,-2,0,7,0,10));Button erase=dangerButton("Effacer rapports, signaux et historique");erase.setOnClickListener(v->confirmDeleteReports());storage.addView(erase,lp(-1,dp(50),0,0,0,0));body.addView(storage,lp(-1,-2,0,0,0,14));LinearLayout privacy=card();privacy.addView(text("Données privées par défaut",18,TEXT,true));privacy.addView(text("L’analyse, les bilans de forme et les profils personnels restent sur ce téléphone. Aucun compte, aucune publicité et aucun transfert automatique.",13,MUTED,false),lp(-1,-2,0,7,0,10));Button guide=outlineButton("Revoir le guide de démarrage");guide.setOnClickListener(v->showWelcome(true));privacy.addView(guide,lp(-1,dp(48),0,0,0,0));body.addView(privacy,lp(-1,-2,0,0,0,14));TextView author=text("H10 Rhythm 4.0 bêta  •  Développé par Mattéo Leroy\nCompatible Polar H10 — projet indépendant, non affilié à Polar Electro.",11,MUTED,false);author.setGravity(Gravity.CENTER);body.addView(author,lp(-1,-2,0,8,0,16));TextView warning=text("Cette application expérimentale ne fournit pas de diagnostic et ne remplace pas un avis médical. En cas de douleur thoracique, malaise, essoufflement important ou perte de connaissance, contacte immédiatement les urgences.",11,0xff738698,false);warning.setGravity(Gravity.CENTER);body.addView(warning,lp(-1,-2,4,0,4,20));return body;
    }

    private void buildNavigation(){
        nav=row();nav.setPadding(dp(8),dp(8),dp(8),dp(8));nav.setBackgroundColor(CARD);
        homeTab=navItem("Aujourd’hui");fitnessTab=navItem("ECG");historyTab=navItem("Forme");settingsTab=navItem("Historique");
        TextView[] tabs={homeTab,fitnessTab,historyTab,settingsTab};for(int i=0;i<tabs.length;i++){final int page=i;nav.addView(tabs[i],new LinearLayout.LayoutParams(0,-1,1));tabs[i].setOnClickListener(v->showPage(page));}
    }
    private void showPage(int page){
        currentPage=page;pageHost.removeAllViews();LinearLayout selected=page==0?homePage:page==1?ecgPage:page==2?fitnessPage:page==3?historyPage:settingsPage;
        ViewGroup parent=(ViewGroup)selected.getParent();if(parent!=null)parent.removeView(selected);ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);scroll.addView(selected);pageHost.addView(scroll,new LinearLayout.LayoutParams(-1,-1));
        TextView[] tabs={homeTab,fitnessTab,historyTab,settingsTab};for(int i=0;i<tabs.length;i++){boolean active=i==page;tabs[i].setTextColor(active?TEAL:MUTED);tabs[i].setBackground(round(active?0xff15332f:0x00000000,0x00000000,14));tabs[i].setSelected(active);}
        if(page==2)refreshFitness();if(page==3)refreshHistory();
    }

    private void refreshHistory(){
        if(timeline!=null){timeline.refresh();today.setText(EventHistory.countToday(this)+" passage(s)");return;}if(historyList==null)return;historyList.removeAllViews();styleHistoryControls();refreshDashboard();List<EventHistory.Record> records=EventHistory.list(this);today.setText(EventHistory.countToday(this)+" passage(s)");String query=historySearch==null?"":historySearch.getText().toString().trim().toLowerCase(Locale.ROOT);long cutoff=historyDays<=0?0:System.currentTimeMillis()-historyDays*86_400_000L;int shown=0;
        for(EventHistory.Record record:records){if(record.timestampMs<cutoff||!matchesFilter(record)||!matchesQuery(record,query))continue;historyList.addView(historyCard(record),lp(-1,-2,0,0,0,12));shown++;}
        if(shown==0){LinearLayout empty=card();TextView icon=text("⌕",34,TEAL,false);icon.setGravity(Gravity.CENTER);empty.addView(icon);TextView title=text(records.isEmpty()?"Rien à signaler pour le moment":"Aucun résultat avec ces filtres",17,TEXT,true);title.setGravity(Gravity.CENTER);empty.addView(title,lp(-1,-2,0,7,0,4));TextView sub=text(records.isEmpty()?"Les passages inhabituels apparaîtront ici avec leur rapport.":"Essaie une autre période, un autre type ou efface la recherche.",13,MUTED,false);sub.setGravity(Gravity.CENTER);empty.addView(sub);historyList.addView(empty,lp(-1,-2,0,0,0,14));}
    }

    private void refreshDashboard(){if(historyStats==null)return;historyStats.removeAllViews();EventHistory.Aggregate events=EventHistory.aggregate(this,historyDays);SessionHistory.Aggregate sessions=SessionHistory.aggregate(this,historyDays);LinearLayout summary=card();summary.addView(text("Vue d’ensemble",18,TEXT,true));summary.addView(text(periodLabel()+" • "+sessions.sessions+" session(s) • "+duration(sessions.durationMs)+" enregistrées",12,MUTED,false),lp(-1,-2,0,5,0,11));LinearLayout first=row();first.addView(dashboardMetric("Passages",String.valueOf(events.total),AMBER),new LinearLayout.LayoutParams(0,dp(72),1));first.addView(dashboardMetric("Battements",String.valueOf(events.premature+events.esa),BLUE),new LinearLayout.LayoutParams(0,dp(72),1));first.addView(dashboardMetric("Pauses",String.valueOf(events.pauses),RED),new LinearLayout.LayoutParams(0,dp(72),1));summary.addView(first);LinearLayout second=row();second.addView(dashboardMetric("FC moyenne",sessions.avgBpm>0?String.format(Locale.FRANCE,"%.0f",sessions.avgBpm):"--",TEAL),new LinearLayout.LayoutParams(0,dp(72),1));second.addView(dashboardMetric("VFC RMSSD",sessions.rmssd>0?String.format(Locale.FRANCE,"%.0f ms",sessions.rmssd):"--",BLUE),new LinearLayout.LayoutParams(0,dp(72),1));second.addView(dashboardMetric("Signal",sessions.signalQuality>0?String.format(Locale.FRANCE,"%.0f %%",sessions.signalQuality):"--",TEAL),new LinearLayout.LayoutParams(0,dp(72),1));summary.addView(second,lp(-1,-2,0,7,0,0));summary.addView(text("La VFC est calculée sur les intervalles propres entre battements normaux. Elle varie avec le repos, l’effort et le contexte ; ce n’est pas un diagnostic.",11,MUTED,false),lp(-1,-2,0,10,0,0));historyStats.addView(summary,lp(-1,-2,0,0,0,12));}

    private View historyCard(EventHistory.Record record){
        LinearLayout card=card();LinearLayout top=row();TextView title=text(publicTitle(record.type,record.title),16,TEXT,true);org.json.JSONObject reportState=LocalRepository.get(this).find("event",record.id);TextView badge=text(record.ready?"PRÊT":reportState!=null&&"failed".equals(reportState.optString("reportState"))?"ÉCHEC":"CRÉATION",10,record.ready?TEAL:AMBER,true);badge.setGravity(Gravity.CENTER);badge.setPadding(dp(9),dp(5),dp(9),dp(5));badge.setBackground(round(record.ready?0xff123a34:0xff3a2d18,record.ready?0xff1e6658:0xff6c5128,30));top.addView(title,new LinearLayout.LayoutParams(0,-2,1));top.addView(badge);card.addView(top);
        card.addView(text(new SimpleDateFormat("EEEE d MMMM • HH:mm:ss",Locale.FRANCE).format(new Date(record.timestampMs)),12,MUTED,false),lp(-1,-2,0,7,0,0));if(record.bpm>0||record.rmssd>0){String metrics=(record.bpm>0?record.bpm+" bpm":"")+(record.rmssd>0?"  •  VFC "+String.format(Locale.FRANCE,"%.0f ms",record.rmssd):"")+(record.signalQuality>0?"  •  signal "+String.format(Locale.FRANCE,"%.0f %%",record.signalQuality):"");card.addView(text(metrics,11,MUTED,false),lp(-1,-2,0,5,0,0));}
        String review="anomaly".equals(record.review)?"Signalé par toi · non confirmé médicalement":"normal".equals(record.review)?"Marqué comme normal":"artifact".equals(record.review)?"Marqué comme artefact":"À vérifier";TextView reviewView=text(review,12,"anomaly".equals(record.review)?RED:"normal".equals(record.review)?TEAL:AMBER,true);card.addView(reviewView,lp(-1,-2,0,6,0,10));
        if(record.ready){LinearLayout reportActions=row();Button report=outlineButton("Ouvrir le PDF");Button share=outlineButton("Partager");reportActions.addView(report,new LinearLayout.LayoutParams(0,dp(44),1));reportActions.addView(share,new LinearLayout.LayoutParams(0,dp(44),1));card.addView(reportActions,lp(-1,-2,0,0,0,9));report.setOnClickListener(v->openReport(record));share.setOnClickListener(v->shareReport(record));}
        else {org.json.JSONObject state=LocalRepository.get(this).find("event",record.id);String detail=state==null?"Passage indisponible":state.optString("reportState").equals("failed")?"Échec de création : "+state.optString("reportError"):"Capture ou création en cours. Environ 30 secondes de contexte après le passage.";card.addView(text(detail,12,MUTED,false),lp(-1,-2,0,0,0,9));if(System.currentTimeMillis()-record.timestampMs>60_000){Button retry=outlineButton("Réessayer la création");card.addView(retry);retry.setOnClickListener(v->{retry.setEnabled(false);new Thread(()->{String result=EventStore.retryReport(this,record.id);runOnUiThread(()->{retry.setEnabled(true);Toast.makeText(this,result,Toast.LENGTH_LONG).show();refreshHistory();});},"retry-report").start();});}}
        Button replay=outlineButton("Revoir le signal et partager les données");card.addView(replay,lp(-1,dp(48),0,0,0,10));replay.setOnClickListener(v->ReplayView.show(this,record));
        LinearLayout actions=row();Button real=smallButton("Inhabituel");Button normal=smallButton("Normal");Button artifact=smallButton("Artefact");actions.addView(real,new LinearLayout.LayoutParams(0,dp(42),1));actions.addView(normal,new LinearLayout.LayoutParams(0,dp(42),1));actions.addView(artifact,new LinearLayout.LayoutParams(0,dp(42),1));card.addView(actions);real.setOnClickListener(v->sendFeedback(record,"anomaly"));normal.setOnClickListener(v->sendFeedback(record,"normal"));artifact.setOnClickListener(v->sendFeedback(record,"artifact"));return card;
    }

    private void sendFeedback(EventHistory.Record record,String label){EventHistory.review(this,record.id,label);if(record.morphology!=null){Intent intent=new Intent(this,MonitorService.class).setAction(MonitorService.ACTION_FEEDBACK);intent.putExtra("label",label);intent.putExtra("morphology",record.morphology);startService(intent);}Toast.makeText(this,"Merci, ton choix a été enregistré.",Toast.LENGTH_SHORT).show();refreshHistory();}
    private void openReport(EventHistory.Record record){Uri uri=EventHistory.findPdf(this,record.id);if(uri==null){Toast.makeText(this,"Le PDF n’est pas encore disponible.",Toast.LENGTH_LONG).show();return;}Intent intent=new Intent(Intent.ACTION_VIEW).setDataAndType(uri,"application/pdf").addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);try{startActivity(intent);}catch(Exception e){Toast.makeText(this,"Installe un lecteur PDF pour ouvrir le rapport.",Toast.LENGTH_LONG).show();}}
    private void shareReport(EventHistory.Record record){Uri uri=EventHistory.findPdf(this,record.id);if(uri==null){Toast.makeText(this,"Le PDF n’est pas encore disponible.",Toast.LENGTH_LONG).show();return;}Intent share=new Intent(Intent.ACTION_SEND).setType("application/pdf").putExtra(Intent.EXTRA_STREAM,uri).addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivity(Intent.createChooser(share,"Partager le rapport ECG"));}
    private void openReportsFolder(){Intent intent=new Intent(Intent.ACTION_OPEN_DOCUMENT).addCategory(Intent.CATEGORY_OPENABLE).setType("application/pdf");try{startActivity(intent);Toast.makeText(this,"Ouvre Documents puis PolarH10Monitor.",Toast.LENGTH_LONG).show();}catch(Exception e){Toast.makeText(this,"Dossier : Documents/PolarH10Monitor",Toast.LENGTH_LONG).show();}}
    private void confirmDeleteReports(){if(running){Toast.makeText(this,"Arrête d’abord l’enregistrement pour effectuer un nettoyage complet.",Toast.LENGTH_LONG).show();return;}new AlertDialog.Builder(this).setTitle("Effacer tout l’historique ?").setMessage("Cette action supprime définitivement les rapports PDF, les ECG bruts exportés, les signaux continus, les bilans de forme, les séances et les résumés de sessions.\n\nLe profil morphologique personnel est conservé.").setNegativeButton("Annuler",null).setPositiveButton("Effacer définitivement",(dialog,which)->insightsWorker.execute(()->{try{int deleted=EventStore.deleteAllStoredData(this);LocalRepository.get(this).clear("morning");getSharedPreferences("fitness_local_v1",0).edit().remove("mornings_v1").apply();TrainingJournal.clear(this);AdaptiveTwin.clear(this);startService(new Intent(this,MonitorService.class).setAction(MonitorService.ACTION_FEEDBACK));runOnUiThread(()->{resetHistoryViews();refreshHistory();refreshFitness();Toast.makeText(this,"Historique remis à zéro • "+deleted+" fichier(s) supprimé(s).",Toast.LENGTH_LONG).show();});}catch(Exception error){runOnUiThread(()->Toast.makeText(this,"Nettoyage incomplet : certains fichiers restent présents. "+error.getMessage(),Toast.LENGTH_LONG).show());}})).show();}

    private void resetHistoryViews(){today.setText("0 passage");homeBeats.setText("--");homeRmssd.setText("--");homeSdnn.setText("--");homeSignalQuality.setText("--");homeEctopy.setText("0");homePauses.setText("0");sessionSummary.setText("Historique vide. La prochaine session repartira de zéro.");lastEventCount=-1;if(historySearch!=null)historySearch.setText("");}

    private void requestAndStart(){ArrayList<String> need=new ArrayList<>();if(Build.VERSION.SDK_INT>=31){if(checkSelfPermission(Manifest.permission.BLUETOOTH_SCAN)!=PackageManager.PERMISSION_GRANTED)need.add(Manifest.permission.BLUETOOTH_SCAN);if(checkSelfPermission(Manifest.permission.BLUETOOTH_CONNECT)!=PackageManager.PERMISSION_GRANTED)need.add(Manifest.permission.BLUETOOTH_CONNECT);}else if(checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)!=PackageManager.PERMISSION_GRANTED)need.add(Manifest.permission.ACCESS_FINE_LOCATION);if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)need.add(Manifest.permission.POST_NOTIFICATIONS);if(!need.isEmpty()){pendingStart=true;requestPermissions(need.toArray(new String[0]),PERMISSIONS);}else startMonitor();}
    @Override public void onRequestPermissionsResult(int request,String[] permissions,int[] results){super.onRequestPermissionsResult(request,permissions,results);if(request==PERMISSIONS&&pendingStart){pendingStart=false;boolean ble=true;for(int i=0;i<permissions.length;i++)if((permissions[i].contains("BLUETOOTH")||permissions[i].contains("LOCATION"))&&results[i]!=PackageManager.PERMISSION_GRANTED)ble=false;if(ble)startMonitor();else Toast.makeText(this,"La permission Bluetooth est nécessaire pour trouver la ceinture.",Toast.LENGTH_LONG).show();}}
    private void startMonitor(){startForegroundService(new Intent(this,MonitorService.class).setAction(MonitorService.ACTION_START));status.setText("Connexion en cours…");}
    private void stopMonitor(){startService(new Intent(this,MonitorService.class).setAction(MonitorService.ACTION_STOP));}

    private void update(Intent intent){
        boolean previousMorning=morningActive;String previousMorningMessage=morningMessage;morningActive=intent.getBooleanExtra("morningActive",false);morningProgress=intent.getIntExtra("morningProgress",0);String receivedMorningMessage=intent.getStringExtra("morningMessage");morningMessage=receivedMorningMessage==null?"":receivedMorningMessage;
        running=intent.getBooleanExtra("running",false);streaming=intent.getBooleanExtra("streaming",false);String state=intent.getStringExtra("status");liveBadge.setText(streaming?"● "+intent.getIntExtra("bpm",0)+" bpm":"EN ATTENTE");status.setText(friendlyStatus(state,running,streaming));statusDot.setTextColor(streaming?RED:running?AMBER:MUTED);device.setText(streaming?intent.getStringExtra("device")+" connectée":running?"Connexion automatique en cours":"Aucune ceinture connectée");
        int heartRate=intent.getIntExtra("bpm",0);bpm.setText(heartRate>0?String.valueOf(heartRate):"--");if(ValueAnimator.areAnimatorsEnabled()&&heartRate>0&&heartRate!=lastDisplayedHeartRate){bpm.animate().cancel();bpm.setScaleX(.92f);bpm.setScaleY(.92f);bpm.animate().scaleX(1f).scaleY(1f).setDuration(220).start();}lastDisplayedHeartRate=heartRate;int batteryLevel=intent.getIntExtra("battery",-1);battery.setText(batteryLevel>=0?batteryLevel+" %"+(intent.getBooleanExtra("batteryStale",false)?" · ancien":""):"-- %");boolean good=intent.getBooleanExtra("signalGood",false),moving=intent.getBooleanExtra("motionActive",false),acc=intent.getBooleanExtra("accActive",false);signal.setText(streaming?(moving?"Mouvement détecté":good?(acc?"Bon • capteur mouvement":"Bon"):"Contact/bruit filtré"):"En attente");
        int learned=intent.getIntExtra("modelSamples",0);boolean ready=intent.getBooleanExtra("modelReady",false);int confirmed=intent.getIntExtra("confirmedExamples",0),artifacts=intent.getIntExtra("artifactExamples",0);modelProgress.setProgress(Math.min(learned,MorphologyModel.BASELINE_TARGET));modelState.setText(ready?"Référence personnelle prête • "+learned+" battements"+(confirmed>0?" • "+confirmed+" anomalie(s)":"")+(artifacts>0?" • "+artifacts+" artefact(s) appris":""):"Apprentissage en cours • "+learned+" / "+MorphologyModel.BASELINE_TARGET+" battements propres");
        int classified=intent.getIntExtra("classifiedBeats",0),uncertain=intent.getIntExtra("uncertainBeats",0);modelState.append("\n"+uncertain+" / "+classified+" battements évalués restent indéterminés.");
        int count=intent.getIntExtra("events",0),rejected=intent.getIntExtra("artifactRejected",0),beatTotal=intent.getIntExtra("beats",0);double rmssd=intent.getDoubleExtra("rmssd",0),sdnn=intent.getDoubleExtra("sdnn",0),quality=intent.getDoubleExtra("signalQuality",0);int early=intent.getIntExtra("esv",0)+intent.getIntExtra("esa",0),pauseCount=intent.getIntExtra("pauses",0);
        homeBeats.setText(beatTotal>0?String.valueOf(beatTotal):"--");homeRmssd.setText(rmssd>0?String.format(Locale.FRANCE,"%.0f ms",rmssd):"--");homeSdnn.setText(sdnn>0?String.format(Locale.FRANCE,"%.0f ms",sdnn):"--");homeSignalQuality.setText(quality>0?String.format(Locale.FRANCE,"%.0f %%",quality):"--");homeEctopy.setText(String.valueOf(early));homePauses.setText(String.valueOf(pauseCount));
        String summary=count==0?"Aucun passage enregistré. Cela n’exclut pas une anomalie.":count+" passage(s) enregistré(s) pendant cette session.";if(rejected>0)summary+=" "+rejected+" forme(s) de bruit écartée(s).";sessionSummary.setText(summary);mainAction.setText(running?"Arrêter l’enregistrement":"Démarrer l’enregistrement");ecgAction.setText(mainAction.getText());mainAction.setBackground(ripple(running?0xff2c1b25:TEAL,running?0xff663244:TEAL,16));mainAction.setTextColor(running?0xffff8fa1:0xff06251f);int epoch=intent.getIntExtra("interruptions",0);if(epoch!=lastSignalEpoch){lastSignalEpoch=epoch;ecg.clear();}float[] wave=intent.getFloatArrayExtra("wave");if(wave!=null)ecg.setSamples(wave,intent.getLongExtra("samples",0));long reportReadyAt=intent.getLongExtra("reportReadyAt",0);if(count!=lastEventCount||reportReadyAt!=lastReportReadyAt){lastEventCount=count;lastReportReadyAt=reportReadyAt;refreshHistory();}
        if(fitnessMorningProgress!=null){fitnessMorningProgress.setProgress(morningActive?morningProgress:fitnessMorningProgress.getProgress());fitnessMorningAction.setText(morningActive?"Annuler le bilan":"Lancer le bilan de 3 minutes");if(morningActive)fitnessMorningStatus.setText(morningMessage);}if((previousMorning&&!morningActive)||(!morningActive&&!morningMessage.equals(previousMorningMessage)))refreshFitness();
    }

    private String friendlyStatus(String raw,boolean running,boolean streaming){if(streaming)return "Enregistrement actif";if(!running)return "Enregistrement arrêté";if(raw==null)return "Connexion en cours…";if(raw.contains("Recherche")||raw.contains("Reconnexion"))return "Recherche de la ceinture…";if(raw.contains("préparation")||raw.contains("Commande"))return "Préparation du signal…";return raw;}
    private String publicTitle(String type,String fallback){switch(type){case"ESV":return"Battement ventriculaire possible";case"ESA":return"Battement auriculaire possible";case"PAUSE":return"Pause inhabituelle";case"IRREGULAR":return"Rythme très irrégulier";case"TACHY":case"REGULAR_TACHY":return"Rythme rapide prolongé";case"BRADY":return"Rythme lent prolongé";case"COUPLET":case"WIDE_RUN":return"Plusieurs battements inhabituels";case"BIGEMINY":case"TRIGEMINY":return"Répétition inhabituelle";default:return fallback==null||fallback.isEmpty()?"Passage à vérifier":fallback;}}
    private Button historyPeriodButton(String label,int days){Button b=smallButton(label);b.setTag(days);periodControls.add(b);b.setOnClickListener(v->{historyDays=days;refreshHistory();});return b;}
    private Button historyFilterButton(String label,String filter){Button b=smallButton(label);b.setTag(filter);filterControls.add(b);LinearLayout.LayoutParams p=lp(dp(104),dp(42),0,0,7,0);b.setLayoutParams(p);b.setOnClickListener(v->{historyFilter=filter;refreshHistory();});return b;}
    private void styleHistoryControls(){for(Button b:periodControls){boolean active=((Integer)b.getTag())==historyDays;b.setTextColor(active?0xff06251f:MUTED);b.setBackground(ripple(active?TEAL:CARD_ALT,active?TEAL:LINE,13));}for(Button b:filterControls){boolean active=historyFilter.equals(b.getTag());b.setTextColor(active?TEXT:MUTED);b.setBackground(ripple(active?0xff1a4050:CARD_ALT,active?TEAL:LINE,13));}}
    private boolean matchesFilter(EventHistory.Record r){if("ALL".equals(historyFilter))return true;if("ARTIFACT".equals(historyFilter))return "artifact".equals(r.review);if("PAUSE".equals(historyFilter))return "PAUSE".equals(r.type);if("IRREGULAR".equals(historyFilter))return "IRREGULAR".equals(r.type);if("RATE".equals(historyFilter))return "TACHY".equals(r.type)||"REGULAR_TACHY".equals(r.type)||"BRADY".equals(r.type);return "ESV".equals(r.type)||"ESA".equals(r.type)||"WIDE_PREMATURE".equals(r.type)||"PREMATURE".equals(r.type)||"COUPLET".equals(r.type)||"WIDE_RUN".equals(r.type)||"BIGEMINY".equals(r.type)||"TRIGEMINY".equals(r.type);}
    private boolean matchesQuery(EventHistory.Record r,String q){if(q.isEmpty())return true;String date=new SimpleDateFormat("dd/MM/yyyy HH:mm EEEE MMMM",Locale.FRANCE).format(new Date(r.timestampMs));String hay=(publicTitle(r.type,r.title)+" "+r.detail+" "+date+" "+r.review).toLowerCase(Locale.ROOT);return hay.contains(q);}
    private String periodLabel(){return historyDays==0?"Depuis le début":historyDays==7?"7 derniers jours":"30 derniers jours";}
    private String duration(long ms){long minutes=ms/60_000L;if(minutes<60)return minutes+" min";return String.format(Locale.FRANCE,"%d h %02d",minutes/60,minutes%60);}
    private View dashboardMetric(String label,String value,int color){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(8),dp(9),dp(8),dp(8));box.setBackground(round(CARD_ALT,LINE,12));TextView l=text(label,9,MUTED,true),v=text(value,15,color,true);v.setSingleLine(true);box.addView(l);box.addView(v,lp(-1,-2,0,5,0,0));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(72),1);p.setMargins(dp(3),0,dp(3),0);box.setLayoutParams(p);return box;}
    private void openBatterySettings(){try{startActivity(new Intent(Settings.ACTION_APPLICATION_DETAILS_SETTINGS,Uri.parse("package:"+getPackageName())));Toast.makeText(this,"Ouvre Batterie puis sélectionne Sans restriction.",Toast.LENGTH_LONG).show();}catch(Exception ignored){}}
    private void openNotificationSettings(){startActivity(new Intent(Settings.ACTION_APP_NOTIFICATION_SETTINGS).putExtra(Settings.EXTRA_APP_PACKAGE,getPackageName()));}
    private void confirmModelReset(){new AlertDialog.Builder(this).setTitle("Recommencer l’apprentissage ECG ?").setMessage("Le profil morphologique des battements sera supprimé. Adaptive Twin, l’historique et les rapports seront conservés.").setNegativeButton("Annuler",null).setPositiveButton("Recommencer",(dialog,which)->{startService(new Intent(this,MonitorService.class).setAction(MonitorService.ACTION_RESET_MODEL));modelProgress.setProgress(0);modelState.setText("L’apprentissage ECG recommencera avec un signal propre.");Toast.makeText(this,"Modèle ECG personnel réinitialisé.",Toast.LENGTH_SHORT).show();}).show();}

    private void showWelcome(boolean force){SharedPreferences prefs=getSharedPreferences("settings",MODE_PRIVATE);if(!force&&prefs.getBoolean("welcome_v40",false))return;Dialog dialog=new Dialog(this);dialog.requestWindowFeature(Window.FEATURE_NO_TITLE);LinearLayout content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(dp(24),dp(24),dp(24),dp(22));content.setBackground(gradient(0xff172738,CARD,0xff315269,24));TextView logo=text("♥",34,RED,true);logo.setGravity(Gravity.CENTER);logo.setBackground(round(0xff351923,0xff6b2c40,18));content.addView(logo,lp(dp(58),dp(58),0,0,0,18));content.addView(text("Bienvenue dans H10 Rhythm Lab",25,TEXT,true));content.addView(text("Un suivi ECG personnel conçu pour rester lisible, même quand l’analyse devient complexe.",14,MUTED,false),lp(-1,-2,0,7,0,12));content.addView(feature("Connecte ta Polar H10","L’application retrouve ensuite automatiquement ta ceinture."));content.addView(feature("Laisse le modèle apprendre","500 battements sélectionnés automatiquement construisent ta référence."));content.addView(feature("Vérifie seulement l’essentiel","Les passages inhabituels et leurs rapports apparaissent dans Historique."));TextView safety=text("Mode laboratoire distinct : aucune alerte cardiaque physique. Les prédictions peuvent être fausses ; ne pas utiliser pour se rassurer.",11,AMBER,false);safety.setPadding(0,dp(16),0,dp(12));content.addView(safety);Button begin=button(force?"Fermer":"Commencer",TEAL,0xff06251f);content.addView(begin,lp(-1,dp(52),0,0,0,0));ScrollView introScroll=new ScrollView(this);introScroll.addView(content);dialog.setContentView(introScroll);Window window=dialog.getWindow();if(window!=null){window.setBackgroundDrawable(new ColorDrawable(0x00000000));window.setDimAmount(.78f);window.addFlags(android.view.WindowManager.LayoutParams.FLAG_DIM_BEHIND);window.setLayout(-1,-2);}begin.setOnClickListener(v->{prefs.edit().putBoolean("welcome_v40",true).apply();dialog.dismiss();});dialog.setOnShowListener(ignored->{Window shown=dialog.getWindow();if(shown!=null)shown.setLayout(getResources().getDisplayMetrics().widthPixels-dp(28),(int)(getResources().getDisplayMetrics().heightPixels*.82));});dialog.show();}

    private void startHeartPulse(){if(statusDot==null||!ValueAnimator.areAnimatorsEnabled())return;if(heartPulse==null){PropertyValuesHolder sx=PropertyValuesHolder.ofFloat(View.SCALE_X,1f,1.18f,1f,1.10f,1f,1f);PropertyValuesHolder sy=PropertyValuesHolder.ofFloat(View.SCALE_Y,1f,1.18f,1f,1.10f,1f,1f);PropertyValuesHolder alpha=PropertyValuesHolder.ofFloat(View.ALPHA,.78f,1f,.86f,1f,.82f,.78f);heartPulse=ObjectAnimator.ofPropertyValuesHolder(statusDot,sx,sy,alpha);heartPulse.setDuration(1450);heartPulse.setRepeatCount(ValueAnimator.INFINITE);heartPulse.setRepeatMode(ValueAnimator.RESTART);}if(!heartPulse.isStarted())heartPulse.start();}

    private LinearLayout page(String eyebrow,String subtitle){LinearLayout body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(16),dp(20),dp(16),dp(30));body.setBackgroundColor(BG);TextView label=text(eyebrow,11,TEAL,true);label.setPadding(dp(10),dp(5),dp(10),dp(5));label.setBackground(round(0xff102e2c,0xff246a5e,30));body.addView(label,lp(-2,-2,0,0,0,8));body.addView(text(subtitle,27,TEXT,true));return body;}
    private LinearLayout card(){LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(dp(16),dp(16),dp(16),dp(16));card.setBackground(gradient(0xff122230,0xff0d1822,LINE,19));card.setElevation(dp(3));return card;}
    private LinearLayout dangerCard(){LinearLayout card=card();card.setBackground(gradient(0xff241720,0xff111922,0xff583044,19));return card;}
    private LinearLayout row(){LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);row.setGravity(Gravity.CENTER_VERTICAL);return row;}
    private TextView miniCard(LinearLayout parent,String label,String value,int color){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(10),dp(12),dp(10),dp(12));int tint=color==BLUE?0xff11263b:color==AMBER?0xff2a2218:0xff102823;box.setBackground(gradient(tint,0xff111c27,color,15));TextView l=text(label,10,MUTED,true),v=text(value,14,color,true);v.setSingleLine(true);box.addView(l);box.addView(v,lp(-1,-2,0,5,0,0));LinearLayout.LayoutParams params=new LinearLayout.LayoutParams(0,dp(76),1);params.setMargins(dp(3),0,dp(3),0);parent.addView(box,params);return v;}
    private TextView sessionMetric(LinearLayout parent,String label,String value,int color){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setGravity(Gravity.CENTER);box.setPadding(dp(5),dp(9),dp(5),dp(8));box.setBackground(round(CARD_ALT,LINE,13));TextView number=text(value,16,color,true);number.setGravity(Gravity.CENTER);number.setSingleLine(true);TextView name=text(label,9,MUTED,true);name.setGravity(Gravity.CENTER);name.setSingleLine(true);box.addView(number);box.addView(name,lp(-1,-2,0,4,0,0));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(66),1);p.setMargins(dp(3),0,dp(3),0);parent.addView(box,p);return number;}
    private View feature(String title,String detail){LinearLayout item=row();TextView icon=text("✓",16,TEAL,true);item.addView(icon,lp(dp(25),-2,0,0,6,0));LinearLayout words=new LinearLayout(this);words.setOrientation(LinearLayout.VERTICAL);words.addView(text(title,14,TEXT,true));words.addView(text(detail,12,MUTED,false),lp(-1,-2,0,3,0,0));item.addView(words,new LinearLayout.LayoutParams(0,-2,1));item.setPadding(0,dp(13),0,0);return item;}
    private TextView navItem(String label){TextView item=text(label,12,MUTED,true);item.setGravity(Gravity.CENTER);item.setBackground(round(0x00000000,0x00000000,14));return item;}
    private TextView text(String value,float sp,int color,boolean bold){TextView view=new TextView(this);view.setText(value);view.setTextSize(sp);view.setTextColor(color);view.setLineSpacing(0,1.12f);if(bold)view.setTypeface(Typeface.create("sans",Typeface.BOLD));return view;}
    private Button button(String label,int fill,int textColor){Button button=new Button(this);button.setText(label);button.setAllCaps(false);button.setTextSize(13);button.setTextColor(textColor);button.setTypeface(Typeface.DEFAULT,Typeface.BOLD);button.setBackground(ripple(fill,fill,16));button.setStateListAnimator(null);return button;}
    private Button outlineButton(String label){return button(label,CARD_ALT,TEXT);}
    private Button dangerButton(String label){Button button=button(label,0xff4a1f2d,0xffffa1b1);button.setBackground(new RippleDrawable(ColorStateList.valueOf(0x33ffffff),gradient(0xff552232,0xff321b27,0xff8a4057,16),null));return button;}
    private Button smallButton(String label){Button button=button(label,CARD_ALT,MUTED);button.setTextSize(10);button.setPadding(dp(2),0,dp(2),0);return button;}
    private GradientDrawable round(int fill,int stroke,int radius){GradientDrawable drawable=new GradientDrawable();drawable.setColor(fill);drawable.setCornerRadius(dp(radius));drawable.setStroke(dp(1),stroke);return drawable;}
    private GradientDrawable gradient(int start,int end,int stroke,int radius){GradientDrawable drawable=new GradientDrawable(GradientDrawable.Orientation.TL_BR,new int[]{start,end});drawable.setCornerRadius(dp(radius));drawable.setStroke(dp(1),stroke);return drawable;}
    private RippleDrawable ripple(int fill,int stroke,int radius){return new RippleDrawable(ColorStateList.valueOf(0x33ffffff),round(fill,stroke,radius),null);}
    private LinearLayout.LayoutParams lp(int width,int height,int left,int top,int right,int bottom){LinearLayout.LayoutParams params=new LinearLayout.LayoutParams(width,height);params.setMargins(dp(left),dp(top),dp(right),dp(bottom));return params;}
    private int dp(int value){return Math.round(value*getResources().getDisplayMetrics().density);}
}
