package com.local.polarh10monitor;

import android.app.Activity;
import android.app.Dialog;
import android.view.Window;
import android.view.WindowManager;
import android.widget.*;
import android.text.InputType;

/** Short profile steps keep actions outside the scroll area and above the keyboard. */
public final class ProfileWizard {
    public static void show(Activity a,Runnable saved){FitnessInsights.Profile p=FitnessInsights.profile(a);Dialog dialog=new Dialog(a);dialog.requestWindowFeature(Window.FEATURE_NO_TITLE);LinearLayout shell=new LinearLayout(a);shell.setOrientation(LinearLayout.VERTICAL);shell.setPadding(24,24,24,24);shell.setBackgroundColor(0xff122230);TextView title=label(a,"Ton profil · 1/3");shell.addView(title);
        ScrollView scroll=new ScrollView(a);LinearLayout form=new LinearLayout(a);form.setOrientation(LinearLayout.VERTICAL);scroll.addView(form);shell.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));
        EditText age=field(a,"Âge",p.age),height=field(a,"Taille (cm)",p.heightCm),weight=field(a,"Poids (kg)",p.weightKg),sport=field(a,"Activité principale",p.sport),goal=field(a,"Objectif personnel",p.goal),moderate=field(a,"Minutes modérées / semaine",p.weeklyModerate),vigorous=field(a,"Minutes soutenues / semaine",p.weeklyVigorous),strength=field(a,"Renforcement : jours / semaine",p.strengthDays),years=field(a,"Années d’entraînement",p.trainingYears);
        CheckBox medication=new CheckBox(a);medication.setText("Traitement influençant la fréquence cardiaque");medication.setTextColor(0xffeff5fa);medication.setChecked(p.hrMedication);
        Spinner sex=new Spinner(a);String[] sexes={"Non renseigné","Femme","Homme"};sex.setAdapter(new ArrayAdapter<>(a,android.R.layout.simple_spinner_dropdown_item,sexes));sex.setSelection(p.sex.equalsIgnoreCase("Femme")?1:p.sex.equalsIgnoreCase("Homme")?2:0);
        LinearLayout actions=new LinearLayout(a);Button back=new Button(a),next=new Button(a);back.setText("Annuler");next.setText("Continuer");actions.addView(back,new LinearLayout.LayoutParams(0,dp(a,56),1));actions.addView(next,new LinearLayout.LayoutParams(0,dp(a,56),1));shell.addView(actions);final int[] step={0};Runnable render=()->{form.removeAllViews();title.setText("Ton profil · "+(step[0]+1)+"/3");back.setText(step[0]==0?"Annuler":"Retour");next.setText(step[0]==2?"Enregistrer":"Continuer");if(step[0]==0){form.addView(label(a,"Tes repères physiques\nL’âge sert aux zones estimées. Poids et taille décrivent leur évolution ; ils ne changent pas artificiellement ta récupération."));form.addView(age);form.addView(height);form.addView(weight);form.addView(label(a,"Sexe facultatif · contexte seulement"));form.addView(sex);}else if(step[0]==1){form.addView(label(a,"Tes habitudes\nCes informations permettent de présenter un suivi adapté."));form.addView(sport);form.addView(goal);form.addView(moderate);form.addView(vigorous);form.addView(strength);form.addView(years);}else{form.addView(label(a,"Dernier point\nUn traitement déclaré suspend l’estimation automatique des zones. Les changements de zones s’appliquent à la prochaine session."));form.addView(medication);form.addView(label(a,"Toutes les informations restent sur ce téléphone. Tu peux les modifier ou les effacer dans les réglages."));}};
        back.setOnClickListener(v->{if(step[0]==0)dialog.dismiss();else{step[0]--;render.run();}});next.setOnClickListener(v->{if(step[0]==0&&(number(age)<16||number(age)>100||number(height)<120||number(height)>230||number(weight)<35||number(weight)>250)){age.setError("Âge 16–100, taille 120–230 cm, poids 35–250 kg");return;}if(step[0]==1&&(number(strength)>7||number(years)>80||number(moderate)>10080||number(vigorous)>10080)){strength.setError("Vérifie les durées et le nombre de jours (0 à 7)");return;}if(step[0]<2){step[0]++;render.run();return;}FitnessInsights.saveProfile(a,new FitnessInsights.Profile(number(age),number(height),number(weight),sex.getSelectedItemPosition()==0?"":sexes[sex.getSelectedItemPosition()],sport.getText().toString().trim(),goal.getText().toString().trim(),number(moderate),number(vigorous),number(strength),number(years),medication.isChecked()));dialog.dismiss();saved.run();});render.run();dialog.setContentView(shell);dialog.setOnShowListener(v->{Window window=dialog.getWindow();if(window!=null){window.setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);window.setLayout(a.getResources().getDisplayMetrics().widthPixels-24,(int)(a.getResources().getDisplayMetrics().heightPixels*.82));}});dialog.show();}
    private static TextView label(Activity a,String text){TextView t=new TextView(a);t.setText(text);t.setTextColor(0xffd4e2ed);t.setTextSize(15);t.setPadding(0,14,0,18);return t;}
    private static EditText field(Activity a,String hint,int value){EditText e=field(a,hint,value==0?"":String.valueOf(value));e.setInputType(InputType.TYPE_CLASS_NUMBER);return e;}
    private static EditText field(Activity a,String hint,String value){EditText e=new EditText(a);e.setHint(hint);e.setText(value);e.setTextColor(0xffeff5fa);e.setHintTextColor(0xff9aafc0);e.setTextSize(16);e.setSingleLine(true);e.setMinHeight(dp(a,56));return e;}
    private static int dp(Activity a,int n){return Math.round(n*a.getResources().getDisplayMetrics().density);}
    private static int number(EditText e){try{return Integer.parseInt(e.getText().toString());}catch(Exception ex){return 0;}}
}
