package com.local.polarh10monitor;

import android.app.Activity;
import android.app.AlertDialog;
import android.app.DatePickerDialog;
import android.graphics.Color;
import android.text.InputType;
import android.widget.*;
import org.json.JSONObject;
import java.util.Calendar;
import java.util.UUID;

/** Journal and supported-load exploration; every action remains local. */
public final class SportsPanel {
    private static TextView text(Activity a,String s){TextView t=new TextView(a);t.setText(s);t.setTextColor(0xffe7eef4);t.setTextSize(14);t.setPadding(0,12,0,12);return t;}
    private static Button action(Activity a,String s){Button b=new Button(a);b.setText(s);b.setAllCaps(false);return b;}
    public static void populate(Activity a,LinearLayout host,Runnable refresh){host.removeAllViews();host.addView(text(a,"Tes séances et ton ressenti"));
        Button add=action(a,"Ajouter une séance");host.addView(add);add.setOnClickListener(v->edit(a,refresh));
        Button complete=action(a,"Confirmer le journal d’hier");host.addView(complete);complete.setOnClickListener(v->new AlertDialog.Builder(a).setTitle("Toutes les séances d’hier sont renseignées ?").setMessage("Confirme aussi une journée de repos. Une journée non renseignée reste inconnue pour l’apprentissage.").setNegativeButton("Vérifier d’abord",null).setPositiveButton("Confirmer",(d,w)->{Calendar c=Calendar.getInstance();c.add(Calendar.DATE,-1);TrainingJournal.completeDay(a,c.getTimeInMillis());refresh.run();}).show());
        Button compare=action(a,"Comparer des séances");host.addView(compare);compare.setOnClickListener(v->compare(a,refresh));
        int n=0;for(JSONObject o:LocalRepository.get(a).list("workout")){if(n++==5)break;Button row=action(a,TrainingJournal.day(o.optLong("time"))+" · "+o.optString("sport")+" · "+o.optInt("minutes")+" min · effort "+o.optInt("rpe")+"/10");host.addView(row);row.setOnClickListener(v->new AlertDialog.Builder(a).setTitle("Séance déclarée").setMessage("Charge descriptive : durée × effort / 5. Le capteur et les séances déclarées ne sont pas additionnés deux fois.").setNegativeButton("Fermer",null).setPositiveButton("Supprimer",(d,w)->{LocalRepository.get(a).delete("workout",o.optString("id"));LocalRepository.get(a).clear("forecast");refresh.run();}).show());}
        host.addView(text(a,"Repères adultes : 150–300 min d’activité modérée par semaine, ou équivalent soutenu, et renforcement au moins 2 jours. Adapte selon tes possibilités et ton suivi médical."));
        Button sources=action(a,"Comprendre les repères");host.addView(sources);sources.setOnClickListener(v->new AlertDialog.Builder(a).setTitle("Source des conseils").setMessage("OMS · Recommandations sur l’activité physique et la sédentarité (2020).\n\nCes repères sont généraux. La FC et la VFC seules ne déterminent ni une maladie ni ton niveau sportif.\n\nhttps://www.who.int/publications/i/item/9789240015128").setPositiveButton("Fermer",null).show());
    }
    private static EditText field(Activity a,String hint,boolean number){EditText e=new EditText(a);e.setHint(hint);e.setSingleLine(true);if(number)e.setInputType(InputType.TYPE_CLASS_NUMBER);return e;}
    private static void edit(Activity a,Runnable refresh){LinearLayout form=new LinearLayout(a);form.setOrientation(LinearLayout.VERTICAL);form.setPadding(24,12,24,12);EditText sport=field(a,"Activité : marche, course, musculation…",false),duration=field(a,"Durée réellement effectuée en minutes",true),effort=field(a,"Effort perçu, de 1 à 10",true);form.addView(sport);form.addView(duration);form.addView(effort);Calendar date=Calendar.getInstance();date.set(Calendar.SECOND,0);date.set(Calendar.MILLISECOND,0);Button day=action(a,TrainingJournal.day(date.getTimeInMillis()));form.addView(day);day.setOnClickListener(v->new DatePickerDialog(a,(picker,y,m,d)->{date.set(y,m,d);day.setText(TrainingJournal.day(date.getTimeInMillis()));},date.get(Calendar.YEAR),date.get(Calendar.MONTH),date.get(Calendar.DAY_OF_MONTH)).show());Button hour=action(a,new java.text.SimpleDateFormat("HH:mm",java.util.Locale.FRANCE).format(date.getTime()));form.addView(hour);hour.setOnClickListener(v->new android.app.TimePickerDialog(a,(picker,h,m)->{date.set(Calendar.HOUR_OF_DAY,h);date.set(Calendar.MINUTE,m);hour.setText(new java.text.SimpleDateFormat("HH:mm",java.util.Locale.FRANCE).format(date.getTime()));},date.get(Calendar.HOUR_OF_DAY),date.get(Calendar.MINUTE),true).show());CheckBox completed=new CheckBox(a);completed.setText("Séance terminée comme prévu");completed.setChecked(true);form.addView(completed);ScrollView scroll=new ScrollView(a);scroll.addView(form);
        AlertDialog dialog=new AlertDialog.Builder(a).setTitle("Ajouter une séance").setView(scroll).setNegativeButton("Annuler",null).setPositiveButton("Enregistrer",null).create();dialog.setOnShowListener(x->dialog.getButton(-1).setOnClickListener(v->{try{int minutes=Integer.parseInt(duration.getText().toString()),rpe=Integer.parseInt(effort.getText().toString());if(sport.getText().toString().trim().isEmpty()||date.getTimeInMillis()>System.currentTimeMillis())throw new IllegalArgumentException();TrainingJournal.add(a,UUID.randomUUID().toString(),date.getTimeInMillis(),sport.getText().toString().trim(),minutes,rpe,completed.isChecked());dialog.dismiss();refresh.run();}catch(Exception ex){duration.setError("Entre une durée de 1 à 1440 min et un effort de 1 à 10, pour une date passée ou aujourd’hui.");}}));dialog.show();
    }
    private static void compare(Activity a,Runnable refresh){LinearLayout form=new LinearLayout(a);form.setOrientation(LinearLayout.VERTICAL);form.setPadding(24,12,24,12);form.addView(text(a,"Choisis une durée et un effort envisagés. Seules les charges et les situations déjà observées peuvent être estimées."));EditText minutes=field(a,"Durée envisagée (minutes), 0 pour repos",true),rpe=field(a,"Effort prévu de 1 à 10",true);form.addView(minutes);form.addView(rpe);TextView result=text(a,"L’estimation s’appuie sur tes journées complètes.");form.addView(result);Button check=action(a,"Explorer"),save=action(a,"Enregistrer cette prévision");form.addView(check);form.addView(save);save.setEnabled(false);final double[] load={0};check.setOnClickListener(v->{try{int m=Integer.parseInt(minutes.getText().toString()),r=Integer.parseInt(rpe.getText().toString());if(m<0||m>180||r<1||r>10)throw new IllegalArgumentException();load[0]=m*r/5.0;final double candidate=load[0];check.setEnabled(false);save.setEnabled(false);result.setText("Comparaison en cours…");new Thread(()->{String answer=AdaptiveTwin.compare(a,candidate,false);a.runOnUiThread(()->{result.setText(answer);check.setEnabled(true);save.setEnabled(true);});},"compare-session").start();}catch(Exception e){minutes.setError("Durée 0–180, effort 1–10");}});save.setOnClickListener(v->{save.setEnabled(false);new Thread(()->{String answer=AdaptiveTwin.compare(a,load[0],true);a.runOnUiThread(()->{result.setText(answer);refresh.run();});},"save-forecast").start();});ScrollView scroll=new ScrollView(a);scroll.addView(form);new AlertDialog.Builder(a).setTitle("Comparer des séances").setView(scroll).setPositiveButton("Fermer",null).show();}
}
